### ISSUE TITLE
accessibility service stops receiving events as soon as habitlab app is closed

### ISSUE THREAD

**Issue by gkovacs** [habitlab/HabitLabMobile#7]
curiously this occurs on my le max 2 (android 6.0.1) but not on my galaxy s3 running lineageos (android 7.1). so it may be device/ROM specific, or specific to particular android versions. probably want to check to see how widespread the bug is?

steps to reproduce

open habitlab app. turn on accessibility service

then close all habitlab windows. open habitlab again. it will prompt that the service is not running ( from checkAccessibilityPermission in PermissionUtil.js )

adding various console.warn to onAccessibilityEvent calls shows that the service continually gets the calls, until the habitlab app is closed.

can be reproduced in the version on the play store as well

will we need to run a foreground service or can this be resolved some other way?

**Comment by DrewGregory** [comment]
If rebuilding the app (i.e. tns debug) you will need to re-enable the Accessibility service. Some older Android versions also require a system restart.
