### ISSUE TITLE
experiment to quantify effects of repeated exposure to interventions on effectiveness and attrition

### ISSUE THREAD

**Issue by gkovacs** [habitlab/HabitLabMobile#8]
objective: see how much showing users an intervention repeatedly has on their retention (hypothesis: after repeated exposure they will uninstall, aka low retention rates) and on efficacy (hypothesis: efficacy aka how long they spent will improve to a point and asymptote off)

interesting things we can then do as follow up:

differences among users for the optimum frequency of showing them an intervention.

ramp up in frequency. so start at every one minute and then increase frequency. or other non-linear approaches

can we detect potential attrition before it actually occurs? for example: perhaps the user starts touching or there's small accelerometer motions that indicate frustration

approach (implementation)

when users install the android app, we vary them among conditions for how frequently we show them the intervention

some have the interventions showing more frequently, some have them showing less frequently

**Comment by gkovacs** [comment]
some things relevant to choosing timing for delivering interventions:

micro randomized trials https://methodology.psu.edu/ra/adap-inter/mrt-projects#proj

just in time adaptive interventions https://methodology.psu.edu/media/techreports/14-126.pdf

**Comment by gkovacs** [comment]
for setting up a mongodb server:

first create heroku app with nodejs and mongodb (if you want an example see https://github.com/habitlab/habitlab-website ) the setup instructions for a nodejs app are on heroku are at https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction and the setup instructions for a mongodb server are at https://elements.heroku.com/addons/mongolab

**Comment by gkovacs** [comment]
stuff we want to log:

during each session:

* when the app was opened
* which message was shown
* when it was closed. also log events when it was switched to/from, if the user switched apps

**Comment by DrewGregory** [comment]
:-)
